language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-2_gavriushova_labs
  - make -j
  - ./matrix_test/matrix_test
  - ./stack_test/stack_test
  - ./multystack_test/multystack_test
  - ./queue_test/queue_test
  - ./list_test/list_test
  - ./stacklist_test/stacklist_test
notifications:
  email: false
